export const PRODUCT_DATA = [
    {
        type: 'Houses',
        sale: true,
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Houses',
        sale: true,
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Houses',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Houses',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Houses',
        sale: true,
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Houses',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Houses',
        sale: true,
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Houses',
        sale: true,
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Smart home',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Smart home',
        sale: true,
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Smart home',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Smart home',
        sale: true,
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Smart home',
        sale: true,
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Smart home',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Smart home',
        sale: true,
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Smart home',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    // Office
    {
        type: 'Apartments',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Apartments',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Apartments',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Apartments',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Apartments',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Apartments',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Apartments',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    // office
    {
        type: 'Office',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Office',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Office',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Office',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },

    {
        type: 'Villa',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Villa',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Villa',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
    {
        type: 'Bungalow',
        img: [
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-2.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-1.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-3.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-4.jpg',
            'https://themesflat.co/html/dreamhomehtml/assets/images/house/featured-5.jpg',
        ],
        title: 'Gorgeous Apartment Building',
        address: '58 Hullbrook Road, Billesley, B13 0LA',
        price: 7500,
        beds: 4,
        baths: 2,
        sqft: 1150,
        compare: 'compare',
        author: {
            name: 'Kathryn Murphy',
            img: 'https://themesflat.co/html/dreamhomehtml/assets/images/author/author-1.jpg'
        },
        days: 3,
    },
]